### ISSUE TITLE
MSI Ranklist soon?

### ISSUE THREAD

**Issue by Animesh-Ghosh** [ankushgarg1998/msit-ranklist#1]
Would it be possible for a _ranklist_ for **MSI** as well? I imagine since the results format is same or quite similar, it would be easy enough?

I think it would be nice if results could be archived (if it's not expensive) for the purposes of keeping record as well.

If there are any problems or suggestions feel free to ping me.

**Comment by ankushgarg1998** [comment]
1. That's a good idea. I'll have to look at a few results PDFs, then I can say if Jimmy (I'm assuming, you've read the Readme.md) can work on it with little or no modification. That'll pretty much decide the amount of work required.

2. I'm assuming, by archiving you mean "to save and show the entire history of marks in all semesters". I'm already working on it.

3. Thanks, Absolutely.

**Comment by Animesh-Ghosh** [comment]
Since both MSIT and MSI are under IPU, I think little modification may be required to Jimmy 🐵 .

I don't know how I will be able to help but I would love to.

**Comment by ankushgarg1998** [comment]
That's great to hear @Animesh-Ghosh . I'll try my best to keep you in the loop with any advancements related to MSI Results.
